### ISSUE TITLE
Docs: broken links for codelists in the schema browser widget (schema-beta-2).

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#136]
**Problem description**
On [this page](http://standard.openownership.org/en/schema-beta-2/schema/schema-browser.html), use the schema browser to look at:

ownership-or-control statement > source > type

This text, in the description for the type property, "Values should come from the source type codelist" links to: http://standard.openownership.org/en/schema-beta-2/_static/docson/index.html#sourcetype. A broken link.

Similar links to codelists are broken throughout the widgets. Those similar links are marked up in json-schema files in this fashion:

`"description": "From the [entityType codelist](#entitytype). What kind of entity is this? The 'registeredEntity' code covers..."`

**When the problem was introduced**
In the master branch this problem didn't occur since descriptions in the schema didn't have these types of links. The links - I guess - were introduced for schema-beta-2 so that on the schema reference pages readers could jump to details of codelists. (For example, see the entityType codelist link in the [entityStatement listing](http://standard.openownership.org/en/schema-beta-2/schema/reference.html#entitystatement).)

**Expected behaviour**
There will be no way for the schema browser widget to 'guess' what page/file it's meant to link to, so I think we just need to strip the link behaviour from the widget text. Alternative suggestions welcome.

**Comment by odscjames** [comment]
So, what we have here is a situation where formatting markup has been put into the actual schema to make one page render correctly but then another page breaks.

I'd want to think about this more, but my initial reaction is it would be better if the schema didn't have this markup in - we are now in a situation we have to make sure the schema renders fine in any tool that might process it. The list of tools might be large and also, other people might want to process the schema in tools we don't know about.

If we took the markup out of the schema files, the question then becomes, can we show the schema in nice rich renderings with links where we want?

And in the case of the schema/reference page, I would hope the answer would be yes - the "jsonschema" widget that renders those tables could probably be changed to detect the "codelist" key that we put in such fields, and then automatically display a link at the end. (Unfortunately, this does also raise the question of how we manage foked/upstream repos, discussed in 19975 in our CRM)

**Comment by kd-ods** [comment]
> I'd want to think about this more, but my initial reaction is it would be better if the schema didn't have this markup in.

I'm inclined to agree. 

Is there anything we can do in the short-term with docson to have it not render hyperlinks at all?

**Comment by odscjames** [comment]
> Is there anything we can do in the short-term with docson to have it not render hyperlinks at all?

Probably, but that will involve a lot of digging around in docson. I'll have a look at this problem generally.

**Comment by odscjames** [comment]
Ok, I've been looking through the docson code. Not rendering hyperlinks at all is difficult, as you can't just ignore them. If you do you'll see things like 

     come from the [source type](#sourcetype) code

Instead, we have to detect them, just use the link text and then not make the link. 

I've been looking through the docson code, and there aren't really any good options.

Either
a) We have to pass through some option on the docson widget.js tag saying "Don't render links" and that has to passed from widget.js to the iframe, from there to docson, and from there into the marked.js library - which is where the link is rendered. But this is a lot of code to maintain as a patch on the upstream library ....
b) A hacky way has been suggested where we use another bit of javascript to remove the link after the docson code has added links. However, due to the iFrame and so on, this would be complex and require a lot of testing in different browsers to make sure it worked.
c) We say we are happy with no links ever at all from docson and put a hack on the openownership master branch to remove all of them - basically https://github.com/OpenDataServices/docson/blob/master/lib/marked.js#L847 function would become "return text", I think.

I'm really not keen on A or B, C is just about bearable but not great. It's a solution that requires technical work to document and maintain in the future, otherwise it will trip someone up.

I would much rather talk about fixing this properly, rather than adding more technical debt to this project.

A) We take all links out of the schema now
B) We do what it takes to fix the translation, as I think this will have just created a bunch of strings with no Russian translation. However, as there will be existing strings in Transifex maybe we can just use them, and strip the link syntax?
C) On pages like http://standard.openownership.org/en/schema-beta-2/schema/reference.html#entitystatement - EntityStatement - Type, we want links to the codelists. Fortunately, we just added a feature to https://github.com/OpenDataServices/sphinxcontrib-jsonschema/tree/openownership to do this - the "externallinks" feature. True, it appears as a "See ___" link at the end, not exactly the same as before, but is that ok? If so, it would take a bit of manual editing to put them all back but it would be doable.

How much of a hassle would step B be - can @rhiaro comment? Can we discuss?

**Comment by rhiaro** [comment]
+1000 fixing it in the schema properly and not messing with the javascript to solve it temporarily. 

I also agree that removing links from the schema text is a good idea anyway, because the schema may be used in different contexts, where links in *any* syntax don't make sense.

Re: step B) I don't see why we can't just strip the link syntax out of the Russian translations. It's just removing the markdown and there should be no understanding of Russian required. So we wouldn't need to involve the translators. Transifex should auto suggest the original translation because the strings will be so similar. I can do a test run in the test transifex project if it would help?

**Comment by kd-ods** [comment]
Yup - I agree that fixing this properly would be best. If @siwhitehouse and @ScatteredInk agree that we should remove these codelist links/markup from the schema descriptions (for the 0.2 release?!) then a Transifex test run would be good, @rhiaro.

**Comment by ScatteredInk** [comment]
Thanks all, I agree with the reasoning for removing these references, and I think we can do this for the 0.2 release.

**Comment by kd-ods** [comment]
So that's a go-ahead for the Transifex test run, @rhiaro. Thanks!

All being well, the next steps would be:

- Edit the bods v0.2 schema (on what branch? Branch off 0.2-dev-ru-translation?)
- Edit the references.rst page of the docs to use the externallinks option to explicitly link to codelists (on what branch? Same branch as above, off 0.2-dev-ru-translation?

**Comment by odscjames** [comment]
Commit https://github.com/openownership/data-standard/commit/2bbb51649901acd8755fa1ecf2375e9f27eec1d0 adds external links - can be cherry-picked to appropriate branch later

**Comment by odscjames** [comment]
https://github.com/openownership/data-standard/pull/236 is ready for review - this does part C.

**Comment by kd-ods** [comment]
(I've requested a change to #236.)

Apart form #236 we still need to do the remaining work; that is, is to remove the codelist link markup from the schema descriptions. But we first need to check that that won't muck up the translations in transifex. @siwhitehouse - once Master is up to date with current translation, is this something you can take a look at?

**Comment by siwhitehouse** [comment]
Previously, uploading strings to Transifex that had just a slight change in mark up caused the whole of the translation of those strings to be lost in the Transifex interface. So I'm going to proceed with caution, although it is possible to add the Russian translation back through the interface as a last resort..

With respect to editing [reference.rst](https://github.com/openownership/data-standard/blob/136-use-externallinks/docs/schema/reference.rst). It looks as though @james has done that in the branch. For instance

`.. jsonschema:: ../_build_schema/components.json
   :pointer: /definitions/Address
   :externallinks: {"type":{"url":"#addresstype","text":"codelist"}}`

I can go through the file and change 'codelist' to 'Codelists' as per Kadie's review of the PR.
What looks like it still needs editing in this example is the components.json file. That still contains:

`"description": "What type of address is this? See the [addressType](#addresstype) codelist.",`. Everything after the '?' can be removed here.

I'll run a test on this example and see how it goes.

**Comment by kd-ods** [comment]
@siwhitehouse - yes, all the .json files in the schema (https://github.com/openownership/data-standard/tree/master/schema) are likely to have description fields with codelists marked up like this.

> "description": "What type of address is this? See the [addressType](#addresstype) codelist.",.

> Everything after the '?' can be removed here.

I think for the moment don't remove everything after the '?'. Let's just remove the link markup in the descriptions, removing '(...)' and then deleting the square brackets, to leave e.g.:

 "description": "What type of address is this? See the addressType codelist."

(I suggest this because actually the whole schema needs a full edit, ideally before 0.3. And it will be easier to do if the mentions of the codelists are left in. To explain, this whole description would read better as: "The type of address, as detailed in the addressType codelist." Or similar.)

**Comment by siwhitehouse** [comment]
I pushed from master up to bods-test in Transifex. This doesn't push up the translations and so I copied across the translation from components.json [in the schema resource in Transifex](https://www.transifex.com/OpenDataServices/bods-v02/translate/#ru/schema--reference/174975866)
I checked out the 136-use-externallinks branch locally.
I edited reference.rst so that it has `"text":"Codelists` in the address block.
I edited the description in components.json so that it reads `"description": "What type of address is this?` ie deleting `See the [addressType](#addresstype) codelist.`
I pushed the two files that had been changed up to the 136-use-externallinks branch.
I rebuilt the version of the 136-use-externallinks branch on RTDs.

Address has the updated description against its type and the link under 'Codelists' does indeed link to the codelist.

I pushed from 136-use-externallinks to bods-test in Transifex and checked the Schema resource. This has not been updated, ie it still contains the deleted text `See the [addressType](#addresstype) codelist.`. I can, and have, deleted the Russian translation of it, but deleting source strings is non-trivial.

According to Transifex:

> [Unfortunately, you can't edit your source strings online because we use them to assure its uniqueness in our databases.
](https://docs.transifex.com/faq/all#is-it-possible-to-edit-source-strings-directly-in-transifex)

> As a workaround, you can add a new target language as an intermediary and make your edits in that language. For example, if your source language is English (en), add English (United Kingdom) (en_GB), then use your edited strings as the "translation" for English (UK). When you're done with the edits, download/pull the "translations" from Transifex, delete the existing online content and upload/push the "translations" back to Transifex as English (en). From there, you can translate the strings to your target languages.

Well that sounds like a right palaver, fraught with the concern that I might overwrite translations if I do it.

**Comment by siwhitehouse** [comment]
@kd-ods The reason why I deleted everything after the '?' is because we are adding "See Codelists" underneath. See http://standard.openownership.org/en/136-use-externallinks/schema/reference.html#address for the test example.

I'm quite happy to edit as you suggest though - it might make Transifex less of a faff.

**Comment by kd-ods** [comment]
@siwhitehouse I think we need the more minimal edit that I suggested (since the description isn't only used on the reference page and needs to be able to stand alone - e.g. in the [schema browser](http://standard.openownership.org/en/master/schema/schema-browser.html#schema-browser-ownership-or-control)). 

Sorry - you may have to repeat that test process :-(

**Comment by siwhitehouse** [comment]
I've edited the files in line with the edit that @kd-ods suggested. So, we can positively review #236 now. I'll take a look at the Transifex side of things in the morning. It will probably blank out the translations in a number of the resources, but we have a record of them in the repo, so we can always edit them back in.

**Comment by siwhitehouse** [comment]
Testing the upload to Transifex. On master branch locally I extracted the strings from the docs and pushed them up to bods-test. Then I added the Russian translation from the live bods-v02 project for `What type of address is this? See the [addressType](#addresstype) codelist. `which is one of the strings that is edited in #236.

Locally I switched branch to 136-use-externallinks. I ran through the process of extracting the strings, re-creating .tx/config so it references bods-test and then pushed the strings up to Transifex.

In Transifex this results in the source string in Eglish changing and the Russian translation being deleted.

**Comment by siwhitehouse** [comment]
Proposed way to align the Russian translation with the updates in 136-use-externallinks is:

Prep
There are some existing gaps in the translation in bods-v02. Record these outside Tx.

Workflow
Go through the diffs in the .json files at https://github.com/openownership/data-standard/pull/236/files. 
For each one copy the Russian translation from the bods-v02 project to bods-test project in Transifex. These should all appear under the 'schema' resource
Go through the process of uploading the changes made in 136-use-externallinks to the bods-v02 project in Transifex
Copy across any translations that have been deleted in the process and edit them so that the link markup is removed

After that we can go through the process of pulling the translation down from Transifex, extracting the strings and pushing them to 136-use-externallinks in the repo, before rebuilding RTDs.

I suspect we will then have "See Codelists" in the Russian translation. Flagging this without giving it any thought just yet.

**Comment by siwhitehouse** [comment]
I've gone through the process as described above. I think that the schema browser now displays as we intended in the English and Russian versions. 

See http://standard.openownership.org/en/136-use-externallinks/schema/schema-browser.html and http://standard.openownership.org/ru/136-use-externallinks/schema/schema-browser.html

@odscjames are you happy to merge the branch (into master) now?

I have noticed that the markup errors that we saw previously on the credits page have returned. I'm pretty sure this is because I edited the .po files and not the .rst.

I'll log that issue separately.

**Comment by odscjames** [comment]
I'm a bit lost in all these comments, but to go back:

> A) We take all links out of the schema now
> B) We do what it takes to fix the translation, as I think this will have just created a bunch of strings with no Russian translation. However, as there will be existing strings in Transifex maybe we can just use them, and strip the link syntax?
> C) On pages like http://standard.openownership.org/en/schema-beta-2/schema/reference.html#entitystatement - EntityStatement - Type, we want links to the codelists. Fortunately, we just added a feature to https://github.com/OpenDataServices/sphinxcontrib-jsonschema/tree/openownership to do this - the "externallinks" feature. True, it appears as a "See ___" link at the end, not exactly the same as before, but is that ok? If so, it would take a bit of manual editing to put them all back but it would be doable.


Part C has been done and merged to master  in #241 
Part A has been done in #242 
Part B needs to be done in pull request #242 - @siwhitehouse will look at that.

**Comment by siwhitehouse** [comment]
#242 reviewed and merged into master

**Comment by siwhitehouse** [comment]
The Russian strings for the parts of the schema edited in #236 are not showing in RTDs as I failed to add the .mo files to the commit.

**Comment by siwhitehouse** [comment]
#243 commits the .mo files and updates RTDs with Russian strings for the parts of the schema edited in #236
