### ISSUE TITLE
Schema & Docs: item descriptions need to be added for all codelists

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#160]

**Comment by stevenday** [comment]
Specifically, when implementing a BODS importer for the OpenOwnership register, I found the following confusing:

- Company types
- Address types for companies
- Address types for people
- Name types for people

**Comment by siwhitehouse** [comment]
Descriptions in codelists should clearly define their codelist item. There should be no potential for confusion about which codelist item should be used.

For instance, we have the [addressType](http://standard.openownership.org/en/v0-1/schema/reference.html#addresstype) codelist which contains both 'residence' and 'home' items. If these are both valid then it must be clear to publishers how they are defined and what distinguishes them.

I'm going to create issues for each codelist that is missing descriptions, so that we can have focused discussions as needs be.

**Comment by ScatteredInk** [comment]
Done.
