### ISSUE TITLE
Docs: Improve guidance around where to put postcodes

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#161]
http://standard.openownership.org/en/v0-1/schema/reference.html#address

**Comment by stevenday** [comment]
Specifically, it would be helpful for the register as a consumer if we could guarantee that the `postCode` was always in the `address` string (or always excluded I suppose). So that we can be sure we've got the 'full' address without trying to work out if we need to append the postcode to the address or not.

**Comment by kd-ods** [comment]
How is this for a proposal: 

- We require publishers to put the postcode in the Postcode field NOT the address field.
- We add a CoVE validation check that the postcode string doesn't appear in the address field.

**Comment by stevenday** [comment]
> We require publishers to put the postcode in the Postcode field NOT the address field.

Thinking aloud really, is this feasible, given that publishers may have already collected data in one single address string? I suppose it's just as feasible as asking them to replicate it into a separate field in that case...

> We add a CoVE validation check that the postcode string doesn't appear in the address field.

The reason I raised this ticket originally was to avoid having to write code to deal with every possible permutation of world postal codes (capitalisation, spacing, hyphenation, prefixes, etc). 

However, I suppose I was coming from an angle of wanting a high degree of correctness, because my code would potentially be mutating data (removing post codes from addresses for example). The validator would be improving correctness even if it just checked for a naive exact match though, so that changes the considerations a lot. 

I presume this would always be an additional check, rather than something which 'fails' validation, because I'm sure there's the potential for false positives in places where codes look similar to street numbers (to use an example I can think of immediately).

**Comment by kd-ods** [comment]
> I presume this would always be an additional check, rather than something which 'fails' validation, because I'm sure there's the potential for false positives in places where codes look similar to street numbers (to use an example I can think of immediately).

Yes - it will have to be some kind of supplementary check since we will never know when data definitely passes/fails this requirement:

- If the postcode field is empty/non-existent, there's no way to determine automatically whether the publisher has put the postcode into the Address field.
- Only if a postcode value exists can we check that it isn't also present in the Address field; and there is the possibility for false positives, as you point out.

Back to your original requirement, @stevenday, "guarantee that the postCode was always in the address string (or always excluded I suppose)". I think the closest we can get to that is us changing our guidance for publishers to the proposal above ("where it exists, put the postcode in the postcode field. And if you know the country, use the country code field", basically) and using the Data Review Tool to point publishers in the right direction.

[So the particular set of user requirements for the Data Review Tool (CoVE) might be sthg along the lines of:

- A 'soft'-validation check which flags where the string in the postcode field is replicated in the Address field.

Plus

- Report the number of addresses in the dataset
- Report the percentage of addresses that have a non-empty postcode field
- Report the percentage of addresses that have a non-empty country code field
]

**Comment by ScatteredInk** [comment]
I agree with the thinking here on using CoVE to push up data quality and not being excessively restrictive at schema level.

In practical terms, then:

- The address description currently says: "This field may also include the postal code".
- We probably want to change this to something along the lines of "Where postal codes are distinguished from addresses in source data, this field SHOULD NOT include the postal code".

**Comment by kd-ods** [comment]
Agreed. I'll make those changes, Jack. And I'll spec up those CoVE checks too.

**Comment by kindly** [comment]
Jacks suggestion looks good, as does the cove check to see if the postcode in the postcode field is duplicated in the address field.

**Comment by kd-ods** [comment]
Building on @ScatteredInk's suggestion:

> Where postal codes are distinguished from addresses in source data, this field SHOULD NOT include the postal code

I'm going to put:

"Where postal codes are isolated fields in source systems, this Address field SHOULD NOT include the postal code."

(Unless there are any objections.)

**Comment by ScatteredInk** [comment]
This is fixed and the CoVE test is described in https://github.com/openownership/lib-cove-bods/issues/16
