### ISSUE TITLE
Knowledge sharing: JSON Schema and CSV Codelist tests

### ISSUE THREAD

**Issue by jpmckinney** [openownership/data-standard#171]
Since OCDS and BODS use the same mechanism for specifying the schema and codelists, I thought it'd be relevant to share scripts we've been improving since August 2017: https://github.com/open-contracting/standard-maintenance-scripts/tree/master/tests

These scripts run on our standard, profiles and extensions to ensure there are no structural errors in our schema and codelists. We use the same Travis configuration across all those repositories, while keeping the tests in one place.

The `test_*.py` files are run by pytest, and each `test_*` method is a test. Each method has a docstring, so it should be easy to understand what each test is doing. A rough summary:

JSON tests

* Ensures all JSON files are valid JSON.
* Ensures all JSON files are formatted for humans (indented).
* Ensures all JSON Schema files are valid JSON Schema Draft 4 and use codelists correctly. Ensures JSON Schema files have required metadata (e.g. title, description) and valid references. There are a variety of subtests in `validate_*` methods:
  * Prints and returns the number of errors relating to the letter case of properties and definitions.
  * Prints and returns the number of errors relating to metadata (title, description, type).
  * Prints and returns the number of errors relating to codelists in a JSON Schema.
  * Prints and returns the number of errors relating to the `type` of `items`.
  * Prints warnings relating to deep objects, which, if appropriate, should be modeled as new definitions.
  * Prints and returns the number of errors relating to objects within arrays lacking `id` fields.
* Ensures a repository has no empty files and an extension has no versioned-release-validation-schema.json file.
* Extension-specific tests

CSV tests

* Ensures all CSV files are valid: no empty rows or columns, no leading or trailing whitespace in cells, same number of cells in each row.
* Ensures all codelists files are valid against codelist-schema.json (you would need to edit the schema, as there are differences in letter-case and column headings)

Readme tests (for extensions)

* Ensures the extension's documentation contains an example.

I'd be happy to work together to factor out common tests where possible, so that we can use a common test suite for our shared way of specifying each standard. The tests can be factored out into a Python package, for example.

**Comment by ScatteredInk** [comment]
Thanks for sharing @jpmckinney, this is really helpful. Once we have the current bit of schema development out of the way, we plan to have a think about testing in the standard repo - so taking this approach sounds great.

**Comment by kd-ods** [comment]
Just to note that I've been getting to grips with the current testing framework in the repo as a result of [this pull request](https://github.com/openownership/data-standard/pull/193)

I'd find it useful to be able to run the tests locally before pushing up changes. If others would find that useful too, let's make it so. And document it well.

**Comment by jpmckinney** [comment]
Do the tests not run locally by running `py.test`?

**Comment by kd-ods** [comment]
@jpmckinney - Yes, it is that easy apparently. A bit of digging around and I've run the tests locally. Now to add some more test files...

**Comment by Bjwebb** [comment]
The OCDS scripts look good - most of these tests should be useful to BODS, with some changes.

My proposal is to first fork the standard-maintenance-scripts repo, and make the changes required to get tests passing for the BODS repo. Then review these changes, and use that to plan a more generic version of the code.

Detailed analysis of running the tests against the BODS repo:

Tests that already pass:
* Ensures all JSON files are valid JSON.
* Prints warnings relating to deep objects, which, if appropriate, should be modeled as new definitions.
* Prints and returns the number of errors relating to the letter case of properties and definitions.
* Ensures a repository has no empty files and an extension has no versioned-release-validation-schema.json file.
* Prints and returns the number of errors relating to the type of items.

Tests that don't need changing, but we need to make a change to the BODS repo:
* Ensures all JSON files are formatted for humans (indented).
  * Some BODS JSON files are not consistently indented. This can be fixed by running an ocdskit command, e.g. https://github.com/openownership/data-standard/commit/0ebf9f8db9044ad63e21addd22248f3909c2a2e1
* Ensures all CSV files are valid: no empty rows or columns, no leading or trailing whitespace in cells, same number of cells in each row.
  * Mostly we just need to open the CSV files in LibreOffice, and save https://github.com/openownership/data-standard/commit/ef2d564b9437e25e635c02eff26a0e64010dccd0, plus a few whitespace changes https://github.com/openownership/data-standard/commit/aefe8dafb242ef1f3a294c362826a8a49b5f3e64
* flake8
  * We should fix flake8 problems in `docs/conf.py`

Note that some of these changes, whilst easy, affect a lot of lines of the relevant files, so is best done and merged when we're not making a lot of other changes.

Require changes to the testing code:
* Ensures all JSON Schema files are valid JSON Schema Draft 4 [and also check there's no additional properties]
  * `version` additional property
* Ensures all codelists files are valid against codelist-schema.json (you would need to edit the schema, as there are differences in letter-case and column headings)
  * Doesn't fail currently because no codelists are checked, because they don't contain `Code`.
* Prints and returns the number of errors relating to metadata (title, description, type).
  * type/title/description are required within the root of `components.json` and with `anyOf`s, which I think we don't want
* Prints and returns the number of errors relating to codelists in a JSON Schema.
   * Fails currently due to capitalised `Code` KeyError
   * When capitalisation is changed there are three enums without codelists, which I think might be deliberate
* non-nullable optional
  * I think we need to disable this for BODS as we don't have merging

Requires further investigation:
* Prints and returns the number of errors relating to objects within arrays lacking id fields.
  * Currently fails to run due to jsonref issues
* Ensures all JSON Schema files use codelists correctly. 
  * Fails I suspect because the codelist directory is different

**Comment by jpmckinney** [comment]
Thanks for reviewing the tests! Happy to collaborate on generic / configurable tests (viz. https://github.com/open-contracting/standard-maintenance-scripts/issues/140).

**Comment by Bjwebb** [comment]
I've created a [fork of the OCDS standard-maintenance-scripts repo](https://github.com/open-contracting/standard-maintenance-scripts/compare/master...Bjwebb:bods).
The tests in this fork pass when applied to the [171-schema-codelists-tests](https://github.com/openownership/data-standard/compare/master...171-schema-codelist-tests) branch of the BODS data-standard repo.

A lot of the changes could be made either to the BODS repo, or to the testing code.

Changes I think should be made in the BODS repo:
* Consistently indent JSON files https://github.com/openownership/data-standard/commit/0ebf9f8db9044ad63e21addd22248f3909c2a2e1
* Tweak formatting of CSV files https://github.com/openownership/data-standard/commit/ef2d564b9437e25e635c02eff26a0e64010dccd0 https://github.com/openownership/data-standard/commit/aefe8dafb242ef1f3a294c362826a8a49b5f3e64
* Fix flake8 errors in `docs/conf.py` https://github.com/openownership/data-standard/commit/a2c37b24f71c14c5f99514ffd7e37bae7403b408

Changes I think should be made in the testing code:
* Disable checks relating for merging, as we don't do this for BODS https://github.com/Bjwebb/standard-maintenance-scripts/commit/dd0ce163fa30af99cc42e03b153fdd7c2ea429bb
* Pass in a base_uri for jsonref (so that we don't need to swtich to absolute URIs) https://github.com/Bjwebb/standard-maintenance-scripts/commit/6bdd141cef7544961242ce85e1204193fd3dd81b
* Disable unused codelist check, as none of the BODS JSON files contain all codelists (which this test assumes) https://github.com/Bjwebb/standard-maintenance-scripts/commit/6ba4e800c3d12bf2b0fd4ce504465f6ebdaa630a
* [Ignore schemapatches.json](https://github.com/Bjwebb/standard-maintenance-scripts/commit/f6b8655525151ebe380518fb63c97370d1e9b912) in the tests. (Since this file is a patch to the schema, and just used for generating fake data, we don't expect to to meet the same constraints as other schemas).

I'm not sure:
* Should we [remove empty technical note columns](https://github.com/openownership/data-standard/commit/5c8289418492753c79ea3552c119f558e6752742) or allow them in the tests?
* Should we [remove version keys from schema files](https://github.com/openownership/data-standard/commit/5e87652032c0feba9ed04b933006acaa143d20ad) or allow them in the tests? (I'm not sure removing these is a good idea, but I think someone suggested it, unless I've got the wrong end of the stick).
* Should we [remove propertyOrder keys](https://github.com/openownership/data-standard/commit/1d2fa69125fc45fa60f5ddb8c24a96134c001757) or allow them in tests? (I think these are used by a certain JSON schema editing software, but I'm not sure what it is, or whether anyone's still using it).
* Should we upercase BODS codelists headings, or [lowercase them in the tests](https://github.com/Bjwebb/standard-maintenance-scripts/commit/ab83154e424a591bfd5f304b3d86e2b857e50031)?
* Should we change the `technical note` to `Note` or [add it to the allowed column headings](https://github.com/Bjwebb/standard-maintenance-scripts/commit/614379d6b77351dde867b23ffae7a84703c883ab#diff-9216eab3fcc96b7d251fd1dfae7c965d) in the tests? Other alternatives to renaming can be seen in the [codelist schema](https://github.com/Bjwebb/standard-maintenance-scripts/blob/master/schema/codelist-schema.json).
* Should we add IDs to arrays of objects in the JSON schemas, or [add exceptions in the tests](https://github.com/Bjwebb/standard-maintenance-scripts/commit/2d69308faa64117afb67144de60d2744e29ac9e6)? (See the exceptions link for a list of which arrays).

I will investigate further:
* Should we add (`title` and `description`) and (`type`, `$ref`, or `oneOf`) to schema objects as required, or [disable the relevant test](https://github.com/Bjwebb/standard-maintenance-scripts/commit/b23492b6efea2f8f5e1e33696c0d135990197020). 
* Should we require that all enums have a codelist, or [add exceptions to the tests](https://github.com/Bjwebb/standard-maintenance-scripts/commit/33418c479f6b2a8bb252487cc2dfb8a187c86569).

**Comment by jpmckinney** [comment]
This is great, thanks! I was thinking we might create a common library to centralize code common to multiple standards (my idea is jscckit for JSON Schema + CSV Codelists, which describes OCDS, BODS, SEDL, etc.)

In that library, the bodies of the test functions can be extracted into methods that yield objects for errors/warnings. The methods can accept configuration parameters. The test files in each standard would then be fairly small, just containing calls to common methods, with parameters as needed.

**Comment by Bjwebb** [comment]
Having a common library makes sense, as does moving the bodies of the tests there.

Creating a common library raises the question of where it should live, and what the procedures around it should be (e.g. who can merge when). We've had a quick chat about this at Open Data Services, and we'll throw our thoughts into a google doc to share next week.

**Comment by Bjwebb** [comment]
@jpmckinney In the next couple of weeks I'm hoping to progress this. Are there any big changes currently planned for https://github.com/open-contracting/standard-maintenance-scripts/tree/master/tests?

**Comment by jpmckinney** [comment]
@Bjwebb Great to hear! We have no planned changes.

I imagine (as a first step, anyway) that this will be about moving the common non-`test_*` methods to a new library, and adding parameters to those methods instead of having hard-coded variables like `required_id_exceptions`, etc.?

Was there a proposal around where the repository should go and how it's governed? I figure we should loop OpenOwnership into that decision.

**Comment by Bjwebb** [comment]
I've discussed governance with @stevenday at Open Ownership, and we're happy for upstream code to sit with Open Contracting for now. This gives us a simpler process, in return for potentially less input. For bodskit/ocdskit and bods-babel/ocds-babel this is more obvious, because we can use the existing OCDS repository. For these tests we might want a new repository (or move functions into ocdskit?).

It looks like for `test_csv.py`, I can just call it from where it is in this repository https://github.com/openownership/data-standard/pull/284/files.
`test_json.py` will require some changes (and `test_readme.py` is not relevant as we don't have extensions). Splitting the non-test functions into a new lib is probably a good approach.

**Comment by jpmckinney** [comment]
I think for test_csv.py we ideally want to be able to configure the header for the code column: https://github.com/open-contracting/standard-maintenance-scripts/compare/bods-reverts#diff-ea560b02be44c268bbc7146106b3756a

I created a new repo https://github.com/open-contracting/jscc (**J**SON **S**chema + **C**SV **C**odelists). We can come up with another name, but it's the main defining feature of OCDS, BODS, etc.

We might eventually move some generic functions from OCDS Kit into that new library, per https://github.com/open-contracting/ocdskit/issues/103.

**Comment by Bjwebb** [comment]
> I think for test_csv.py we ideally want to be able to configure the header for the code column: https://github.com/open-contracting/standard-maintenance-scripts/compare/bods-reverts#diff-ea560b02be44c268bbc7146106b3756a

Yes, or change the BODS codelists headings.

**Comment by Bjwebb** [comment]
Proposal for next steps on this:
* Include JSON tests (and parts of tests) that pass already (or with minor changes), moving code into jscc as I go. (And documenting what tests are missing because they don't pass)  [~1.5 days]
* Codelist tests exactly as they are, with the necessary changes made to this repo (e.g. upercase headings, Notes instead of "technical note") [~1 day]

**Comment by Bjwebb** [comment]
@jpmckinney Am I right in thinking jscc should only include code that is applicable across standards? e.g. so all tests about extensions should stay where they are?

**Comment by jpmckinney** [comment]
Yes, that sounds good to me :)

**Comment by Bjwebb** [comment]
One thing these tests do is check that JSON schemas have the expected fields. Currently, `propertyOrder` fails the validation, as a its not a JSON schema key. I could special case this, or just remove the key, as I don't think we need it any more. @timgdavies Am I right to think the `propertyOrder` key isn't useful any more?

**Comment by timgdavies** [comment]
We were using `propertyOrder` so that we could generate nice forms for training materials with https://github.com/json-editor/json-editor - but it's not formally part of the schema, so I suppose it can move out of there.

**Comment by Bjwebb** [comment]
Aha, I thought it was probably something to do with your initial modelling. Happy to leave it in if we're still using it.

**Comment by timgdavies** [comment]
If it's not a problem to leave in, let's do that. We can review as we work on the next release whether we want to keep it or not.

**Comment by Bjwebb** [comment]
Okay, I've updated my PR to leave it in https://github.com/openownership/data-standard/pull/303/files#diff-0f8529efc62011b2f7a649151c0f6984R24-R26

**Comment by jpmckinney** [comment]
I refactored, tested and documented jscc. See in particular: https://jscc.readthedocs.io/en/latest/api/testing/checks.html

Should this issue be closed?

**Comment by Bjwebb** [comment]
Thanks for the work on jscc!

I'll close this issue. There's some work here that's not yet done, but I've opened new issues:
* [Update test_json.py in this repo to use the refactored jscc](https://github.com/openownership/data-standard/issues/307)
* [Update CSV tests in this repo to use jscc](https://github.com/openownership/data-standard/issues/306)
* [Run codelist specific checks (in addition to generic csv checks)](https://github.com/openownership/data-standard/issues/308)

**Comment by Bjwebb** [comment]
No, I've deleted it.
