### ISSUE TITLE
Example data framework: ownership structures, disclosure regimes, and disclosure conditions

### ISSUE THREAD

**Issue by ScatteredInk** [openownership/data-standard#173]
In the lead up to BODS 1.0, we’d like to move towards a more coherent set of example data for the Standard. The examples should:

*  Guide publishers to the right publishing pattern for a particular ownership structure;
*  Work across the standard documentation and implementation guidance to illustrate both technical features and major policy decisions; 
*   Ensure that BODS 1.0 covers the full known range of ownership structures, changes to state, and constraints on disclosure.

The canonical examples are _not_ intended as a replacement for individual country example datasets, which would be tailored for particular circumstances.

### Proposed definition for BODS example data

Our examples are the **BODS data** produced by an **ownership structure** under a particular **disclosure regime.**

*   **BODS data** refers to:
    1. JSON data that passes all _schema_ _validation_ and _additional_ _checks_ according to an agreed version of the BODS Data Review Tool that uses version 0.2 of the BODS schema;
    2. Data released at bods-package level (i.e., list as root), unless otherwise specified;
    3. Data that is packaged at the level of the _disclosing entity_. For example, in an indirect ownership structure where Company A is the disclosing entity and Person 1 controls Company A through Company B:
        *   Only statements made by Company A about the ownership structure **_should_** be included in the package;
        *   Company B may itself report on part of the ownership structure but these statements **_should not_** be included in the package;     
        *   Depending on the rules of the disclosure regime, Company A may make statements about (i) its ownership _by_ Company B and (ii) the ownership _of_ Company B. These statements **_should_** be included in the package.

*   An **ownership structure** refers to some relationship between a legal entity or arrangement and a natural person or legal entity or arrangement, or a set of such relationships. The relationship may be direct or indirect (i.e., there may be intermediary legal or natural persons or arrangements between the endpoints of the relationship) and it may include relationships of beneficial ownership, legal ownership and formal and informal control.

*   A **disclosure regime** refers to the rules a disclosing entity must follow when providing information about its ownership structure (i.e. the threshold that determines a beneficial owner, methods of control to be disclosed, triggers to update information, or any information that must be withheld).

BODS data produced by an ownership structure and disclosure regime may be further modified by **disclosure conditions**: 

*   **Disclosure conditions** refers to: 
    1. What is known to the disclosing entity about those parts of the ownership structure relevant to the disclosure regime at the time that a disclosure is made (i.e., imperfect knowledge may result in a disclosing entity declaring that its owner, or some entity in its ownership structure, is unknown or known only as a result of a third-party declaration); and,
    2. The information, if any, that a disclosing entity chooses to disclose in a beneficial ownership declaration.

Over time, a disclosing entity may have to make multiple statements about its ownership that reflect changes to its ownership structure, status or external circumstances. Collectively these triggers to replace data can be called **state changes**.    

*   A **state change** may be the result of:    
    1. A change to the ownership relationships within an ownership structure.
    2. A change to the details of the natural persons or entities within an ownership structure.
    3. A change to the disclosure regime or disclosure conditions.
    4. A change to the status of the declaring entity, i.e. an inactive entity is no longer expected to provide statements.
    5. A change to the status of the publisher, i.e. no further statements are expected from this publisher.  

By combining ownership structures, disclosure regimes, disclosure conditions and state changes, we can create the BODS example data required.

### Example

For example, `os-03` below is a simple indirect ownership structure. The dashed line represents Person 1's total interest in Company A of 30% shares and votes. In the ownership structure, we have perfect knowledge and can see that the interest is held through Company B.

![os-03](https://user-images.githubusercontent.com/7060780/58017305-c610a080-7af7-11e9-9697-0b26a5b0d50a.png)

Below is the same ownership structure seen through a disclosure regime `dr-02` with a 25% threshold to declare a beneficial owner, where disclosures are banded and where only the beneficial owner is disclosed. Significant amounts of information about the ownership structure `os-03` are lost under this system.

![os-03b-dr-02](https://user-images.githubusercontent.com/7060780/58017707-c8bfc580-7af8-11e9-8038-5ba075f33037.png)

### Implementation

If this approach is agreed then:

*   Future example data will be created using this framework, rather than on an ad hoc basis;
*   Example data will be built using defined ownership structures and disclosure regimes that, where appropriate, are modified by disclosure conditions and state changes.
* Lists of ownership structures etc will be developed collaboratively in separate issues.
* A standard naming structure for examples in the repository would make it clear which ownership structure etc was being used, e.g. a file with the name 'os-01-dr-03.json' would refer to the ownership structure with id `01` and the disclosure regime with id `03`. It may also be necessary to identify the disclosing entity in complex ownership structures, or multipart examples, using a format like 'os-01-dr-03-company-a.json'.

### Timeline

The aim would be to have this in place for the 0.3 release (but the indirect ownership examples will use this format for 0.2).

**Comment by stevenday** [comment]
This seems a good general taxonomy, naming strategy, etc, but is it going to suffer from a bit of an explosion of examples? I already count nearly 100 examples you're going to need to produce (19 Ownership structures x 5 disclosure regimes) and that's without any state changes. Whilst I think it would no doubt be a valuable experience to produce all of these at least once, maintaining them all with future schema changes is going to be a headache!

Perhaps that's an unavoidable burden of documenting a flexible standard, but I wonder if there's a way to document things in our *ideal* disclosure regime (or maybe the most verbose) and then have more limited examples for others? I imagine a lot could be inferred from the most verbose disclosure regime + some rules? Alternatively, perhaps this points to a need from some automated tooling to generate derivatives from the most verbose examples?

This also doesn't really detail how the state change bit will fit into the structure. Can you 'id' state changes globally in the same way, or are they specific to ownership structures? I know I've struggled to get a handle on all the distinct permutations when thinking about them, so I'm punting some hard work here, but it would be good to flesh out the plan for them a bit more, because I think they're really key to getting good data in the end.

**Comment by ScatteredInk** [comment]
> I wonder if there's a way to document things in our ideal disclosure regime (or maybe the most verbose) and then have more limited examples for others? I imagine a lot could be inferred from the most verbose disclosure regime + some rules?

Yes, I agree. I have been classifying the organisational examples into 'core' and 'non-core' for this purpose. I suspect that we will be able to whittle down that core group into the tricky ones that need extensive documentation and coverage as the standard develops.

> This also doesn't really detail how the state change bit will fit into the structure. Can you 'id' state changes globally in the same way, or are they specific to ownership structures? I know I've struggled to get a handle on all the distinct permutations when thinking about them, so I'm punting some hard work here, but it would be good to flesh out the plan for them a bit more, because I think they're really key to getting good data in the end.

Yes, I think is going to be the hard work for 0.3 when we will lock down change-over-time. Things are vague right now because this area is not well developed.

**Comment by kathryn-ods** [comment]
We have updated the example data for 0.4, stripping out some examples and adding some new ones and the naming has been made more consistent - it's just descriptive now which I think is easier to use. I'm not sure whether a more structured review is needed for 1.0?

**Comment by kd-ods** [comment]
Things have moved on since this thread was opened. I think the content and structure of the docs now deals with the first two bullets:

> - Guide publishers to the right publishing pattern for a particular ownership structure;
> - Work across the standard documentation and implementation guidance to illustrate both technical features and major policy decisions;

We have a whole 'Modelling requirements' section where 'Representing X/Y/Z' pages can be found. And within them we have sets of Examples. The Key concepts page has been brought up to date too.

On the third bullet:

> - Ensure that BODS 1.0 covers the full known range of ownership structures, changes to state, and constraints on disclosure.

I think the reservations expressed by our colleagues earlier in the thread were borne out: the bullet expressed a fine goal (BODS needs to be extensive and flexible) but the example data framework as envisaged never got off the ground. The way to that goal is not documenting every permutation of BO structure and disclosure regime. The size of the task makes it impossible.

We can therefore close this issue.
