### ISSUE TITLE
User request for data entry and collection: Flat file templates

### ISSUE THREAD

**Issue by anderspeders** [openownership/data-standard#21]
For *government/registration agencies* conducting *data collection* from countries with limited ICT capacity, information management systems or limited data collection practises for company registration I think it would be useful to have easily assessible data entry methods available. One option could be to provide *flat file templates* which could be used for manual spreadsheet based data entry without requiring any webbased platforms.

To provide some additional context on the current data collection and dissemination capacity gap among EITI countries which are all requested to implement BO data collection over the coming years:  Only 12 out of 46 EITI countries are publishing currently collected EITI data in machine readable format. 

Assuming that far from all countries will be able to implement local webform based applications or adopt global submission applications, it would be important to have spreadsheet templates which can capture the data.

This might be outside the scope of the schema itself but I think it would be useful to prioritize for the near term future for example as part of pilot country projects.

**Comment by timgdavies** [comment]
This is a really good point.

We have an approach used in OCDS [that lets us generate flat templates](http://flatten-tool.readthedocs.io/en/latest/create-template/) that can be converted into structured data directly, but still very much built around the data model, rather than user data entry forms.

I've run a quick generation of a version below:

[flat-template.xlsx](https://github.com/openownership/data-standard/files/835934/flat-template.xlsx)

(There is more we could do with additional information in the schema to guide the generation of these templates in a more user-friendly sort of way).

However, I suspect designing really good Excel data entry interface for collection of information would involve more than just the flattened representation of the data that can be transformed into structure data - it will involve carefully setting up validations etc.

**Comment by timgdavies** [comment]
@kd-ods has been leading on work to develop spreadsheet templates for extractives data with EITI. 

This work is tracked separately from the standard, so I'm closing this issue. Anyone interested in those templates should contact Kadie or support@openownership.org
