### ISSUE TITLE
Updating the Releases page

### ISSUE THREAD

**Issue by siwhitehouse** [openownership/data-standard#265]
It looks like the [Releases page](https://github.com/openownership/data-standard/releases) is out of date. The page gets as far as the 0.1-beta release but no further.

We should document how we record releases and then add something to the [dev-handbook](https://github.com/openownership/bods-dev-handbook/blob/d1b1ca407a005feec22eaa278b1a49072daffc10/standard_releases.md) so that this is done every time we release a new version of BODS.

Now we have decided upon the versioning format of vX-Y-Z the documentation should include whether we record all versions or just vX-Y

**Comment by timgdavies** [comment]
@stevenday @siwhitehouse Am I right in understanding that our branch approach to releases means the [releases page](https://github.com/openownership/data-standard/releases) will not be updated in future? 

In which case, I would suggest either:

(a) removing the releases that are there;

(b) creating a release with a description that points people to where to find the latest releases;

I think (a) is preferable and is unlikely to break anything for anyone.

**Comment by stevenday** [comment]
@timgdavies - I was unaware that we were using this github feature until now, but you're right - it's not really compatible with us maintaining release branches rather than tags. I'll do a) now. In any case ReadTheDocs keeps a list of versions for us that is automatically updated, so there's no need to duplicate it.
