### ISSUE TITLE
Update licence and contributor agreement info in docs

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#282]
Following the update of the main [licence info](https://github.com/openownership/data-standard/blob/master/LICENSE) in the repo #278 - we will need to update the text in the [docs About page](https://github.com/openownership/data-standard/blob/master/docs/about/index.rst). There's also a link there to the [contributor agreement](https://github.com/openownership/data-standard/blob/master/CONTRIBUTING.md); I'm not sure what the status of that doc is now (esp. given that it refers only to the 'Open Ownership Register').

Any such changes to the docs will have implications for the translations.

@stevenday @timgdavies @Bjwebb - any thoughts on the status of the contributor agreement?

**Comment by stevenday** [comment]
Good spot @kd-ods!

I think we should change the text about copyright holders just as we did in the LICENSE file, and it would be worth doing this as part of our current tech sprint, to get the changes in place for translators to look at asap afterwards.

On the contributor agreement, I don't really know what the value of having it is, especially one that doesn't require explicit signed agreements from contributors. We already have a license chosen because it provides explicit coverage of contributors (Apache 2.0). That said, if we're happy with it seems like the project is only mentioned in that one place, so it could easily be updated?

**Comment by kd-ods** [comment]
Closing. Updating the about docs is now part of the ['freeze checklist'](https://github.com/openownership/bods-dev-handbook/blob/master/standard_releases.md#freeze-checklist).
