### ISSUE TITLE
jscc: Use csv tests from jscc

### ISSUE THREAD

**Issue by Bjwebb** [openownership/data-standard#306]
Currently, we use standard-maintenance-scripts for CSV tests. However, the shared code has now been moved out to [jscc](https://github.com/open-contracting/jscc). We should write our own `test_csv.py` that imports it from there instead.

Note: there's docs at https://jscc.readthedocs.io/en/latest/api/testing/checks.html

**Comment by Bjwebb** [comment]
Once this is done, we can drop all usage of standard-maintenance scripts. Instead of using their install.sh, we should just be able to directly install the latest refactored jscc, which will pull in all dependencies it needs.

**Comment by jpmckinney** [comment]
I haven't moved across all the tests from https://github.com/open-contracting/standard-maintenance-scripts/blob/master/tests/test_csv.py

I figure that can be done as part of this. The main changes I typically had to make are:

* Return `errors` instead of asserting that it is zero
* Add keyword parameters for any standard-specific logic
* Add a warning class for each new method

I also left some of the directory tree walking in the original test files.
