### ISSUE TITLE
Suggestion: rename interestLevel property

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#319]
The possible values for this are: direct, indirect and unknown.

The name of this property is too easily confused with the extent or share of the interest. (e.g. 10%, 15-25%)

Alternative suggestions: 'directness', 'isDirect' (though boolean-ising is problematic as it sidelines the unknown option)

**Comment by timgdavies** [comment]
Good call. I've been increasingly uncomfortable with this property name.

**Comment by rhiaro** [comment]
My concern is that "directness" may not be clear for non-native English speakers (or even for native English speakers). The dictionary definition is "bluntness", "candor", "forthrightness" etc. rather than "how direct something is" so I'm not sure it's technically a word in the sense that we want to use it here. 

Maybe `interestDirectLevel`, `directLevel`, or `howDirect` ? I prefer `isDirect` too to be honest, if it still pulls from a codelist I don't think the fact it sounds boolean is a huge problem, though I can see it might lead people to use true/false values instead of looking at the codelist.

**Comment by kd-ods** [comment]
I'd be happy with `directOrIndirect`.

**Comment by Blueskies00** [comment]
Implemented in BODS 0.3.
