### ISSUE TITLE
Fix inconsistent formatting in codelists

### ISSUE THREAD

**Issue by ScatteredInk** [openownership/data-standard#341]
Most of our codelists use camelCase.

Two of our codelists, unspecifiedReason and interestType use a dash delimited format.

I think it makes sense to have everything use camelCase and update the style guide, where this issue was first raised.

**Comment by kd-ods** [comment]
@rhiaro - assigning to you to do asap since the documenting aspect will unblock a lot of other work this sprint :-)

There are some related meta-issues, which I've also assigned to you, about documenting the process for updating and managing codelists, and the styleguide:

- https://github.com/openownership/bods-dev-handbook/issues/6
- https://github.com/openownership/bods-dev-handbook/issues/21

To get you started, take a look at the [codelists placeholder info here](https://github.com/openownership/bods-dev-handbook/blob/master/compiling_schema.md#codelists).
