### ISSUE TITLE
[BUG] - Text clipped/exceeding limits in SVG diagrams

### ISSUE THREAD

**Issue by lgs85** [openownership/data-standard#456]
A number of pages have diagrams where the text is cut off in SVG diagrams. Usually this is edge labels in Spanish or Russian. I've been able to identify the following:

 - The bottom diagram in [this Spanish translation](https://standard.openownership.org/es/0.3.0/primer/whyisbo.html) on why BO is a useful concept
- Very minor but a datetime object goes outside the boundaries of the diagram area in the [statements as claims](https://standard.openownership.org/en/latest/schema/concepts.html#statements-as-claims) section (all translations)
- The [Spanish](https://standard.openownership.org/es/0.3.0/schema/guidance/repr-beneficial-ownership.html) and [Russian](https://standard.openownership.org/ru/0.3.0/schema/guidance/repr-beneficial-ownership.html) translations of the representing beneficial ownership guidance
- In the [Spanish](https://standard.openownership.org/es/0.3.0/schema/guidance/repr-state-owned-enterprises.html) and [Russian](https://standard.openownership.org/ru/0.3.0/schema/guidance/repr-state-owned-enterprises.html) translations on state-owned enterprises (text outside limits of text box)
- Text obscured by a triangle in the [Russian](https://standard.openownership.org/ru/0.3.0/primer/whatisthebods.html) translation of What is the BODS

**Comment by kathryn-ods** [comment]
Note - I did some research into whether SVG 2 would fix this. It might in the future but not right now.

**Comment by kd-ods** [comment]
@kathryn-ods, so we'll have to adjust these diagrams by hand to make extra space for text. Actually, I think the diagrams to focus on are only:

- The [Spanish](https://standard.openownership.org/es/0.3.0/schema/guidance/repr-beneficial-ownership.html) and [Russian](https://standard.openownership.org/ru/0.3.0/schema/guidance/repr-beneficial-ownership.html) translations of the representing beneficial ownership guidance
- In the [Spanish](https://standard.openownership.org/es/0.3.0/schema/guidance/repr-state-owned-enterprises.html) and [Russian](https://standard.openownership.org/ru/0.3.0/schema/guidance/repr-state-owned-enterprises.html) translations on state-owned enterprises (text outside limits of text box)

... since the Primer pages are getting an edit (#416) and the Key concepts page is being rewritten.

I've assigned this to you, @kathryn-ods. That OK?

**Comment by kathryn-ods** [comment]
Thanks @kd-ods will look at this next week

**Comment by kathryn-ods** [comment]
@kd-ods I've made those changes in https://github.com/openownership/data-standard/tree/diagram-edits

As per https://github.com/openownership/bods-dev-handbook/blob/main/style_guide.md I've switched Courier New out for Arial and that saved enough space in the SOE example. 

@Blueskies00 you happy for me to also switch the fonts out in the other SOE diagrams for consistency?
