### ISSUE TITLE
[BUG] - Russian translation formatting issues

### ISSUE THREAD

**Issue by lgs85** [openownership/data-standard#457]
A Russian translator has identified several formatting issues. Several of these are related to SVGs and picked up in #456. Others are:

- untranslated hyperlinks in the [about](https://standard.openownership.org/ru/0.3.0/about/index.html) page
- RST formatting issues on the [schema index](https://standard.openownership.org/ru/0.3.0/schema/index.html) page
- Possible formatting issues on the [schema concepts](https://standard.openownership.org/ru/0.3.0/schema/concepts.html) page (this was flagged though I'm not completely clear why)
- Possible formatting issues on the [schema reference](https://standard.openownership.org/ru/0.3.0/schema/reference.html) page
- Possible formatting issues on the [serialization](https://standard.openownership.org/ru/0.3.0/schema/guidance/serialization.html) page

**Comment by Blueskies00** [comment]
Disclaimer: I've only ever learnt minimal Russian and Cyrillic using Duolingo so apologies if my understanding of the original issues is completely wrong!

> untranslated hyperlinks in the [about](https://standard.openownership.org/ru/0.3.0/about/index.html) page

- Specifically the word "data" in this line: Открытая рабочая группа по разработке стандарта data
- Specifically the word "credits" in this line: Ознакомьтесь с credits,
- Also minor formatting - a unnecessary colon at the end of this line: заполнив эту форму:
- Also minor formatting - potentially unneeded comma (my Russian grammar knowledge is even more non-existent!) after the untranslated word in this line: Ознакомьтесь с credits,

>RST formatting issues on the [schema index](https://standard.openownership.org/ru/0.3.0/schema/index.html) page

- Specifically a space missing between и and the bold formatting asterisks, causing the asterisks to display instead of rendering the text bold on the website in this line: ДОЛЖЕН и\*\*СЛЕДУЕТ** используются в схеме для обозначения обязательных и рекомендуемых элементов Стандарта, как определено в RFC2119.
- Also minor formatting - potentially needed Oxford comma after the word "опубликования" in this line : Дополнительные аспекты касательно валидации, опубликования и жизненного цикла
(that's my best guess for this one, again based on no knowledge of Russian grammar)

>Possible formatting issues on the [schema concepts](https://standard.openownership.org/ru/0.3.0/schema/concepts.html) page

- "Это известно под названием битемпорального моделирования." Couldn't tell with this one, sorry!
- "интеллектуальной интеграции информации между разными фактами раскрытия информации, наборами данных и разным временем." This seems to contain the duplication of the word different (разными) in two parts of the sentence, and doesn't seem to flow. (Aligns with the original comment around coherence.)
For clarity: In English it says "intelligent integration of information across disclosures, datasets and time". The Russian literally translates as "intelligent integration of information across **different** disclosures, datasets and **different** times".

>Possible formatting issues on the [schema reference](https://standard.openownership.org/ru/0.3.0/schema/reference.html) page

- "или код подразделения юрисдикции (ISO 3166-2)." Based on the original comments, I understand the issue here to be a case of the words we use in English for the concept not translating very well, perhaps too literal and out of local context?

>Possible formatting issues on the [serialization](https://standard.openownership.org/ru/0.3.0/schema/guidance/serialization.html) page

- "Строки JSON МОГУТ также использоваться для создания крупных файлов." The English version refers to JSON **Lines**. The word "Строки" translates as **strings**, so I'm assuming this is a point around the technical uses of the word and how it's been translated here.

**Comment by kathryn-ods** [comment]
@kd-ods can this be closed as we're now about to rerun translation? Or is it useful for awareness for @odscrachel?

**Comment by kd-ods** [comment]
We need to keep it open and then check, at the end of the new translation process, whether the 0.3 issues have been resolved or have diappeared. So assigning to Rachel.

**Comment by kd-ods** [comment]
@odscrachel - when you start looking at the Russian translation, can you see if any of these formatting issues are still relevant?

**Comment by odscrachel** [comment]
We have checked the new translation for the issues mentioned here. For those that still look to exist (JSON lines/credits link and format/ISO 3166-2 text) we have asked the reviewer to take a look and change appropriately for the language.

**Comment by odscrachel** [comment]
Issues addressed
