### ISSUE TITLE
Delete Functional Requirements Page

### ISSUE THREAD

**Issue by kathryn-ods** [openownership/data-standard#556]
Review of https://standard.openownership.org/en/latest/schema/guidance/functional-requirements.html

**Comment by kathryn-ods** [comment]
https://docs.google.com/document/d/1TUy7pEVo5gJSFNlinOLPCaR5ZGLglk80zn5nMkSQ0kc/edit?usp=sharing edits will be recorded here

**Comment by kathryn-ods** [comment]
@kd-ods I think all the content in this page will be covered elsewhere in the schema/docs (see notes in gdoc). Is it useful to have it on this page as well? I think we should delete it.

**Comment by kd-ods** [comment]
I agree @kathryn-ods: I don't think we need this page any more.

But let's not delete the rst page yet on the main branch. Let's keep this ticket live so that we can check that the page content has been adequately covered elsewhere when we do the final docs read-through before the 0.4 freeze.

I'll rename this ticket to 'Delete...' and put it back into the 'ready' column now.

**Comment by kathryn-ods** [comment]
We're also deleting the sources and annotations page - thought it might be easier to track all pages for deletion here
