### ISSUE TITLE
Resolve questions over implementation of multiple serialisations of BODS data

### ISSUE THREAD

**Issue by robredpath** [openownership/data-standard#57]
In our updated modelling, we anticipate up to three kinds of BODS serialisation.

**(1) Array of statements**

E.g. 

```json
[
  {
    "id": "e9eeaaa3-d4d0-4036-8f47-731c5ddbf6c8",
    "type": "personStatement",
    "name":"Ed Example"
  },
  {
    "id": "d9cf4a36-fe23-4842-9dbe-5766f8744a05",
    "type": "entityStatement",
    "name":"E.G Corporation"
  },
  {
    "id": "e1fe7861-0494-406d-82c3-670652a9544c",
    "type": "beneficialOwnershipStatement",
    "subject": {
      "entity": {
        "identifiedByStatementID": "d9cf4a36-fe23-4842-9dbe-5766f8744a05"
      }
    },
    "interestedParty":{
        "person":{
            "identifiedByStatementID":"e9eeaaa3-d4d0-4036-8f47-731c5ddbf6c8"
        }
    }
  }
]
```

**(2) Statement JSON lines**

I.e. each statement on a single line.

```jsonl
{"id": "e9eeaaa3-d4d0-4036-8f47-731c5ddbf6c8","type": "personStatement","name":"Ed Example"}
{"id": "d9cf4a36-fe23-4842-9dbe-5766f8744a05","type": "entityStatement", "name":"E.G Corporation"}
{"id": "e1fe7861-0494-406d-82c3-670652a9544c","type": "beneficialOwnershipStatement","subject": {"entity": {"identifiedByStatementID": "d9cf4a36-fe23-4842-9dbe-5766f8744a05"}},"interestedParty":{"person":{"identifiedByStatementID":"e9eeaaa3-d4d0-4036-8f47-731c5ddbf6c8"}}}
```

**(3) Nested API responses**

Provided as an array of beneficial ownership statements, where the person and entity statements are nested. The below is only a draft, as we may want to consider API standard approaches for this. 

This would be recommended **only** for interactive API responses.

```
[
  {
    "id": "e1fe7861-0494-406d-82c3-670652a9544c",
    "type": "beneficialOwnershipStatement",
    "subject": {
      "entity": {
        "id": "d9cf4a36-fe23-4842-9dbe-5766f8744a05",
        "type": "entityStatement",
        "name": "E.G Corporation"
      }
    },
    "interestedParty": {
      "person": {
        "id": "e9eeaaa3-d4d0-4036-8f47-731c5ddbf6c8",
        "type": "personStatement",
        "name": "Ed Example"
      }
    }
  }
]
```

**Comment by timgdavies** [comment]
We may not want option 3 at all (as this goes back towards nested structure that we're trying to get away from). 

Agreeing API patterns for publishing statements may be a separate issue.

**Comment by timgdavies** [comment]
From discussion - we would have `statementType` as property to identify the statement. A groupID to support replacements. 

```json
[
  {
    "id": "e9eeaaa3-d4d0-4036-8f47-731c5ddbf6c8",
    "groupID":"8f47-731c5ddbf6c8-e9eeaaa3-d4d0-4036",
    "statementType": "personStatement",
    "name":"Ed Example"
  }
]
```

**Comment by kindly** [comment]
@timgdavies I agree that I am not sure about option 3.  I think we need to consider an API more carefully than this as it may contain may useful endpoints i.e who this organization beneficially owns and vice versa, or a way to get the ownership tree even deeper. 
So just looking an individual ownership statement might not be enough.

As to option 2 (jsonlines) I am still not certain about it due to human readability issues.  So it is only really for developer ease of use.  As a developer I would much prefer to receive and process a ".json" file than a ".jsonlines" file unless the file was very large.

**Comment by ScatteredInk** [comment]
@kindly I agree that option 2 has readability issues. But the primary use-case for it, I think, is for streaming changes from publishers' systems, where the chunks of information that make up a beneficial ownership statement are likely to be updated independently of each other. Companies House in the UK has been planning to implement a system like this for a while: http://forum.aws.chdev.org/t/psc-streaming-api/529  

> As a developer I would much prefer to receive and process a ".json" file than a ".jsonlines" file unless the file was very large.

For comparison, the prototype JSON Lines export from OpenOwnership (basic company data and some ownership information from the UK plus a small amount of data from elsewhere) was 4.2GB.

**Comment by ScatteredInk** [comment]
Some context on why we have been considering the move from a nested to a flat serialisation:

1. Arrays of statements make explicit the underlying data model that we are trying to represent. In combination with a `statementType` property for each statement in the top-level array, the implied tabular structure of our data becomes clear; consuming systems can use this property, for example, to pipe statements to the correct tables in a database.

2. Validation of the data becomes easier. In BODS, validation of the data according to the schema is not sufficient to ensure that it is correct. Among other things, we want to be sure that every entity and natural person statement referenced in a beneficial ownership statement is contained in the package-level statement. We can take advantage of the orderedness of arrays to do this, using secondary validation to check that any statement identifiers referenced in a beneficial ownership statement have already been seen earlier in the array.

3. A flattened serialisation is easier to use at scale. We gain the ability to reuse statements where appropriate, rather than always duplicating information. Command line tools like jq are powerful but complex and, with simpler data structures, data queries and transformations on bulk exports will be easier to write and understand. A possible JSON Lines serialisation will also make streaming updates to beneficial ownership statements possible, using the `replacesStatement` and `groupID` properties.

**Comment by timgdavies** [comment]
Our approach to Serialization is documented at http://standard.openownership.org/en/0.2.0/schema/guidance/serialization.html 

Whilst this does not show a JSON Lines example, I think it does the job for now.
