### ISSUE TITLE
identifiers - registration status?

### ISSUE THREAD

**Issue by kathryn-ods** [openownership/data-standard#729]
I'm currently working on the GLEIF mapping and LEIs have a registration status - they can lapse or be retired or annulled. We're using an annotation to reflect this for this mapping. Are there other cases where identifiers have a status? Is this something that should be represented in the schema?

**Comment by kd-ods** [comment]
I think GLEIF data is a bit of a special case. GLEIF is primarily an identifier-issuing authority so the purpose of their data is to publish the identifiers and registration status of organisations, so that these identifiers can be re-used elsewhere as references. (Their level 2 data goes beyond that prime purpose, and - being about relationships between entities - is a piece of the BO puzzle. It's their level 2 data that we're interested in from a BO perspective, rather than the registration process.)

Identifiers as they appear in most BO data are references to an organisation which is already registered. 

So to the questions:

> Are there other cases where identifiers have a status?

Yes - anywhere where identifiers are minted as part of a formal organisation registration process.

> Is this something that should be represented in the schema?

No, I think that would be mission-creep. BODS isn't a standard for registration authorities sharing identifier and organisation status information.

Those are my reckons. Have I missed any obvious rationale for the opposing view?

**Comment by kathryn-ods** [comment]
> Those are my reckons. Have I missed any obvious rationale for the opposing view?

I don't think so - this sounds reasonable to me
