### ISSUE TITLE
Correction and redaction of data

### ISSUE THREAD

**Issue by timgdavies** [openownership/data-standard#9]
> An issues related to the [draft conceptual model](https://github.com/openownership/data-standard/issues/7)

Data publishers may wish to update previously published data, or in some cases, request removal/redaction of previously published data.

The use of unique and persistent statement identifiers can facilitate this, but a documented set of approaches for this may be required.

Comments on appropriate approaches are welcome.

**Comment by jpmckinney** [comment]
I like the approach of having a separate log for these sorts of events, like the way many systems maintain an 'audit trail' of user activity.

**Comment by kd-ods** [comment]
Here's a direct question from a prospective publisher relating to this issue of error correction (and my reply):

"**2) Sometimes we produce bad data, which gets later annulled. In case of beneficial ownership, it happens when the chain of control is complicated and notaries make mistakes when interpreting it. So, if the according statements are published, how can we annul them? For instance, should we proceed this way: publish new void statement that replaces the old statement? From the documentation it is not clear to me when to use “replacesStatements” element. Should it be used for (1) error correction or (2) data update?**
BODS is still being developed towards a v1 release and we may refine how replacesStatements works. However, as things stand it should be used for both error correction and for data updates. Yes, in order to effectively 'delete' a previous statement, publishing a new void statement to replace it is acceptable. If you wish to correct something in a statement, then you should (1) replace it with a new statement, (2) use replacesStatements to link to the overwritten statement, and then - optionally and for clarity - (3) use the Annotations feature to point to the corrected information (using the 'correcting' value for Motivation).

**Do inactive statements mean that they are good historical statements? If yes, then how to tell that some historical statements are bad and should not be treated as good historical datasets.**
This is where a clearly communicated publication process and publication cadence from the publisher is crucial. Data users will need to know at what point and under what circumstances they can expect to see previous statements replaced. As a data user, you would need to go to the original publisher of the statements and check for updates before knowing with what confidence you can trust the 'accuracy' of the statements. A clear publication cadence could assist with this.

For example, our current thinking is that you should publish the up-to-date, full set of statements (complete dataset) on a weekly or monthly basis. In between those full snapshots you should publish - perhaps on a daily or even hourly basis - all new statements from the last day or hour (including corrections and 'deletions'). This way, someone can construct an up-to-date dataset by taking the last full snapshot and appending to it all the statements since released."

**Comment by kd-ods** [comment]
On the voiding question, it is currently very messy to void statements in BODS 0.2. For example, you have to choose what sort of statement to use as a voiding statement and then comply with property requirements. If you choose to use an ownership-or-control statement, this is how you'd need to do it:

```
{
    "statementID": "1dc0e987-5c57-4a1c-b3ad-61353b66a9b7",
    "replacesStatements": ["a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a17"],
    "publicationDetails": {
        "publicationDate": "2020-10-08",
        "bodsVersion": "0.2",
        "publisher": {
            "name": "Register of Enterprises, CountryX"
        }
    },
    "statementType": "ownershipOrControlStatement",
    "interestedParty":{
        "describedByEntityStatement": ""
    },
    "isComponent": false,
    "subject": {
        "describedByEntityStatement": ""
    },
    "annotations":[
        {
            "statementPointerTarget": "/replacesStatements",
            "motivation": "commenting",
            "description": "Voiding previous statement. Statement no longer active."
        }
    ]
}
```

And could/should I just extend the replacesStatements array to include all statements in a previous declaration that are being voided? Or just all the ownership-or-control statements in that prior declaration? What is the concept of a declaration and can I just void all statements made in the past year? Who knows.

**Proposal: introduce a new statement type, voidingStatement** 

```
{
    "statementID": "1dc0e987-5c57-4a1c-b3ad-61353b66a9b7",
    "replacesStatements": ["a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a17",”a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22”],
    "statementType": "voidingStatement",
    "voidingReason": "part-of-declaration-update"
    "publicationDetails": {
        "publicationDate": "2020-10-08",
        "bodsVersion": "0.2",
        "publisher": {
            "name": "Business Register, CountryX"
        }
    }
    "source": {
        "type": "selfDeclaration",
        "description": "update number 0004955938537",
        "assertedBy": [
            {
                "name": "ArtTech Group Ltd."
            }
        ]
    }
}
```
This statement type could cover redaction and and other use cases. A `voidingReason` codelist would be constructed to cover the main use cases and support data use. Suggested items:

* part of declaration update
* redaction
* declaration correction
* inference
* declaration no longer current

Some of these items refer to the concept of a 'declaration' which doesn't currently exist in BODS 0.2. Related proposal is in #334.

**Comment by kathryn-ods** [comment]
Closing this ticket - BODS 0.4 includes features for modelling change over time and guidance on correction/redaction
