### ISSUE TITLE
Separating arrangements and agreements

### ISSUE THREAD

**Issue by ScatteredInk** [openownership/data-standard#92]
Arrangements are a broad category in the current release, covering trusts and joint shareholding. This is creating some complexity.

An alternative might be to separate arrangements from agreements, with their own statmenent types, where:

**Arrangements** are non-registered entities able to *enter into* legal or beneficial ownership relationships.

| Arrangement type  | Description |
| ------------- | ------------- |
| `trust`  | A trust |
| `unincorporatedJointVenture` | A joint venture (which might own assets) |

Arrangements **can** be both the subject and interested party in beneficial ownership statements.  

**Agreements** exist between entities and **join, modify or set conditions** on legal or beneficial ownership relationships.

Agreements **cannot** be either the subject or the interested party of beneficial ownership statements. Beneficial ownership statements can be linked to agreements using the `partOfArrangement` field. 

| Agreement type  | Description |
| ------------- | ------------- |
| `jointShareholding`  | A joint shareholding (two or more natural persons have equal rights to the same interest). |
| `contract` | A contract that defines beneficial ownership rights beyond those otherwise implied by ownership structures.  |
| `conditionalContract` | An agreement that defines conditions by which beneficial ownership rights could come into existence | 

The major use-case for agreements is cases where we want to describe a situation where multiple parties are associated with a single interest in an entity (as with a joint shareholding) and want to minimise the uncertainty of beneficial ownership disclosures, and limit the possibilities for adversarial use, by linking these statements together.

An example joint shareholding, where two natural persons share the rights to a 100% interest, could therefore be represented as:

```
[
  {
    "statementID":"agreement-id-1",
    "statementType":"agreementStatement",
    "agreementType":"jointShareholding"
  },
  {
    "statementType":"beneficialOwnershipStatement",
    "statementID":"1",
    "subject":{
      "entity":{
        "describedByStatement":"company-id-1",
        "type":"entity"
      }
    },
    "interestedParty":{
      "person":{
        "describedByStatement":"person-id-1",
        "type":"person"
      }
    },
    "interests":[
      {
        "type":"shareholding",
        "share":{
          "exact":100
        }
      }
    ],
    "partOfArrangement":"agreement-id-1"
  },
  {
    "statementType":"beneficialOwnershipStatement",
    "statementID":"2",
    "subject":{
      "entity":{
        "describedByStatement":"company-id-1",
        "type":"entity"
      }
    },
    "interestedParty":{
      "person":{
        "describedByStatement":"person-id-2",
        "type":"person"
      }
    },
    "interests":[
      {
        "type":"shareholding",
        "share":{
          "exact":100
        }
      }
    ],
    "partOfArrangement":"agreement-id-1"
  }
]
```

**Comment by timgdavies** [comment]
Let me check my understanding here, as I'm not convinced of the need for new statement types... though that may be because I'm missing something. 

## Current approach
In the case of a joint shareholding we record that:

* Person P [ is 100% shareholder of ] an arrangement A [ that is 100% shareholder of ] Company C
* Person Q [ is 100% shareholder of ] an arrangement A [ that is 100% shareholder of ] Company C 

This involves two person statements (Person P, Person Q) three beneficial ownership statements (Person P -> Arrangement; Person Q -> Arrangement; Arrangement -> Company), and two entity statements (Arrangement; Company)

It is then it is up to consuming applications to know about the 'types' of entity and arrangement, and apply the correct logic when working out whether to infer that Person P can be said to own 50% of Company C.

## The proposal

The proposal above introduces the idea of an 'agreement'. In this approach:

* Person P [ is 100% shareholder of ] Company C
* Person Q [ is 100% shareholder of ] Company C 

The two beneficial ownership statements involved (P->C, Q->C) are then related to an `agreementStatement` which expresses a condition on the relationship (`jointShareholding`). 

## Considerations

* In the current model, it does seem 'odd' to say that two people who are joint shareholders in a company are, actually, full shareholders in some artificial 'arrangement' entity which then 'owns' the company. 

However:

* The proposed model means that it *not possible* to apply a validation rule that where `interestType` = shareholding, the total of share between any set of people and companies should add up to 100%.

* In the proposal, we have to introduce a new `partOfArrangement` field to associate two beneficial ownership statements together. In the earlier model these could be associated simply by noting that they point to the same arrangement. 

And, I'm not sure whether these fall for or against the proposed model, but:

* We should consider how this looks in spreadsheet data, and how self-contained beneficial ownership data can be made (we should minimise the number of statements that need to be discovered to understand an ownership chain) 

* We have the concept of `direct` or `indirect` interests in the current model. This codelist could be extended to capture `viaArrangement` or `viaAgreement` semantics.

* I suspect some of the reasoning behind proposal above rests on the definition or arrangement as "non-registered entities able to enter into legal or beneficial ownership relationships". 

* We have the idea of `annotations` on an `Interest` which were intended to capture any conditions that relate to the particular interest (e.g. the conditions of any agreement - though admittedly only in semi-structured way right now). 

## The alternative

Sticking with the simple model of:

- Person Statements
- Entity Statements (including arrangements, and possibly agreements)
- Beneficial Ownership Statements

we look at how to document the types of these and logics to apply to them in more detail. 

Visually and in our documentation and validation we can draw a clear distinction between entity statements that can be at the terminus of a beneficial ownership chain, and those that should not.

**Comment by ScatteredInk** [comment]
Closing this and will move the interest types forward in #10.
